=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/RobotInfo.dtd
<!ELEMENT Robots (Robot*)>
<!ELEMENT Robot (Name, Description, EntityName)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT EntityName (#PCDATA)>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/Common/RobotInfo.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Robots SYSTEM "RobotInfo.dtd">
<Robots>

  <Robot>
    <Name>Bender</Name>
    <Description>I have no description.</Description>
    <EntityName>green_robot</EntityName>
  </Robot>

  <Robot>
    <Name>I, Robot</Name>
    <Description>Blah</Description>
    <EntityName>orange_robot</EntityName>
  </Robot>

  <Robot>
    <Name>Terminator</Name>
    <Description>Foo, this is a description.</Description>
    <EntityName>blue_robot</EntityName>
  </Robot>

  <Robot>
    <Name>Marvin</Name>
    <Description>Gugus.</Description>
    <EntityName>purple_robot</EntityName>
  </Robot>

</Robots>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/RobotInfo.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Robots SYSTEM "RobotInfo.dtd">
<Robots>

  <Robot>
    <Name>Givayo</Name>
    <Description>I have no description.</Description>
    <EntityName>green_dwarf</EntityName>
  </Robot>

  <Robot>
    <Name>Famar</Name>
    <Description>Blah</Description>
    <EntityName>orange_dwarf</EntityName>
  </Robot>

  <Robot>
    <Name>Tunira</Name>
    <Description>Foo, this is a description.</Description>
    <EntityName>blue_dwarf</EntityName>
  </Robot>

  <Robot>
    <Name>Yrogr</Name>
    <Description>Gugus.</Description>
    <EntityName>purple_dwarf</EntityName>
  </Robot>

</Robots>
