=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/Common/Levels.dtd
<!ELEMENT Level (Includes?, Entity*)>
<!ELEMENT Includes (Include*)>
<!ELEMENT Include EMPTY>
<!ELEMENT Entity (Attributes?, Properties?)>
<!ELEMENT Attributes (Attribute*)>
<!ELEMENT Properties (Property*)>
<!ELEMENT Attribute EMPTY>
<!ELEMENT Property EMPTY>
<!ATTLIST Include
  name CDATA #REQUIRED
>
<!ATTLIST Entity
  name ID #REQUIRED
  abstract CDATA "false"
  extends CDATA #IMPLIED
>
<!ATTLIST Attribute
  name CDATA #REQUIRED
  template (string|int|float|float2|float3|quaternion|bool) #REQUIRED
  value CDATA #REQUIRED
>
<!ATTLIST Property
  name CDATA #REQUIRED
  type CDATA #REQUIRED
  active CDATA "true"
>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/Instances/4Noobs/Renderer.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Level SYSTEM "../../Common/Levels.dtd">
<Level>

  <Includes>
    <Include name="Level\Common\Renderer\Templates.xml"/>
  </Includes>

  <Entity name="respawn_spot" extends="respawn_spot_base">
  </Entity>

  <Entity name="lavafire" extends="lavafire_base">
  </Entity>

  <Entity name="snow" extends="snow_base">
    <Attributes>
      <Attribute name="particles_per_second" template="float" value="200"/>
    </Attributes>
  </Entity>

  <Entity name="fog" extends="fog_base">
  </Entity>
 
  <Entity name="lava" extends="lava_base">
  </Entity>

  <Entity name="environment" extends="environment_base">
  </Entity>

  <Entity name="lights" extends="lights_base">
    <Attributes>
      <Attribute name="sky_light_color" template="float3" value="0.8 1.6 2"/>
      <Attribute name="lava_light_color" template="float3" value="0.6 0.5 0.4"/>
      <Attribute name="spot_light_color" template="float3" value="1.85 1.85 1.85"/>
    </Attributes>
  </Entity>

  <Entity name="tonemapping" extends="tonemapping_base">
    <Attributes>
      <Attribute name="bloom_sensitivity" template="float3" value="0.25 0.0 0.0"/>
      <Attribute name="bloom_intensity" template="float3" value="1.3 0.9 0.0"/>
      <Attribute name="base_intensity" template="float3" value="0.87 0.8 1.0"/>
      <Attribute name="bloom_saturation" template="float3" value="0.5 0.8 1.0"/>
      <Attribute name="base_saturation" template="float3" value="1 0.5 1"/>
      <Attribute name="in1" template="float3" value="1 1.4 1"/>
      <Attribute name="out1" template="float3" value="1 1.1 1"/>
      <Attribute name="in2" template="float3" value="2 2.7 2"/>
      <Attribute name="out2" template="float3" value="2 5 2"/>
    </Attributes>
  </Entity>

  <Entity name="topoverlay" extends="topoverlay_base">
    <Attributes>
      <Attribute name="strength" template="float" value="0.5"/>
    </Attributes>
  </Entity>

</Level>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/Templates.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Level SYSTEM "Levels.dtd">
<Level>

  <Includes>
    <Include name="Level\RobotTemplates.xml"/>
    <Include name="Level\IslandTemplates.xml"/>
  </Includes>
  
  <!-- abstract game entities (templates) -->


  <Entity name="camera_base" abstract="true">
    <Attributes>
      <Attribute name="kind" template="string" value="camera"/>
      <Attribute name="position" template="float3" value="0 420 1065"/>
      <!--Attribute name="position" template="float3" value="0 420 1065"/-->
      <Attribute name="target" template="float3" value="0 180 0"/>
      <Attribute name="up" template="float3" value="0 1 0"/>
      <Attribute name="fov" template="float" value="33"/>
      <Attribute name="near_clip" template="float" value="1"/>
      <Attribute name="far_clip" template="float" value="10000"/>
    </Attributes>
    <Properties>
      <Property name="camera" type="ProjectMagma.Simulation.CameraProperty"/>
    </Properties>
  </Entity>

  <Entity name="lava_base" abstract="true">
    <Attributes>
      <Attribute name="kind" template="string" value="lava"/>
      <Attribute name="position" template="float3" value="0 0 0"/>
      <!--Attribute name="scale" template="float3" value="0.8 0.12 0.8"/-->
      <Attribute name="scale" template="float3" value="800 120 800"/>
      <!--Attribute name="scale" template="float3" value="1200 4 1200"/-->
      <!--Attribute name="mesh" template="string" value="Models\Environment\lava6c_wrongdir"/-->
      <Attribute name="mesh" template="string" value="Models\Environment\lava6c"/>
      <!--Attribute name="mesh" template="string" value="Models\Primitives\lava_primitive"/-->
      <Attribute name="sparsestucco_texture" template="string" value="Textures/Lava/sparsestucco"/>
      <Attribute name="firefractal_texture" template="string" value="Textures/Lava/firefractal"/>
      <Attribute name="vectorcloud_texture" template="string" value="Textures/Lava/vectorclouds"/>
      <Attribute name="granite_texture" template="string" value="Textures/Lava/granite"/>
    </Attributes>
    <Properties>
      <Property name="render" type="ProjectMagma.Simulation.LavaRenderProperty"/>
      <!--Property name="render" type="ProjectMagma.Simulation.BasicRenderProperty"/-->
      <Property name="render_highlight" type="ProjectMagma.Simulation.RenderHighlightProperty"/>
    </Properties>
  </Entity>


  <Entity name="pillar_base" abstract="true">
    <Attributes>
      <Attribute name="kind" template="string" value="pillar"/>
      <Attribute name="position" template="float3" value="230 0 260"/>
      <Attribute name="scale" template="float3" value="200 200 200"/>
      <Attribute name="bv_type" template="string" value="alignedbox3tree"/>
      <Attribute name="diffuse_texture" template="string" value="Textures/Environment/environ_diffuse"/>
      <Attribute name="lava_light_strength" template="float" value="1.0"/>
      <Attribute name="diffuse_color" template="float3" value="1.0 1.0 1.0"/>
      <Attribute name="specular_color" template="float3" value="0.05 0.05 0.05"/>
      <Attribute name="env_ground_waves_amplitude" template="float" value="15.0"/>
      <Attribute name="env_ground_waves_frequency" template="float" value="0.002"/>
      <Attribute name="env_ground_waves_hardness" template="float" value="5.5"/>
      <Attribute name="env_ground_waves_velocity" template="float" value="0.003"/>
    </Attributes>
    <Properties>
      <Property name="collision" type="ProjectMagma.Simulation.Collision.CollisionProperty"/>
      <Property name="render" type="ProjectMagma.Simulation.EnvironmentRenderProperty"/>
      <Property name="render_highlight" type="ProjectMagma.Simulation.RenderHighlightProperty"/>
    </Properties>
  </Entity>

  <Entity name="cave_base" abstract="true">
    <Attributes>
      <Attribute name="kind" template="string" value="cave"/>
      <Attribute name="position" template="float3" value="0 -20 90"/>
      <Attribute name="scale" template="float3" value="800 800 800"/>
      <Attribute name="mesh" template="string" value="Models/Environment/cave_grp"/>
      <Attribute name="bv_type" template="string" value="alignedbox3tree"/>
      <Attribute name="diffuse_texture" template="string" value="Textures/Environment/cave_diffuse_v001"/>
      <!--Attribute name="diffuse_texture" template="string" value="Textures/custom_uv_diag"/-->
      <Attribute name="lava_light_strength" template="float" value="1.0"/>
      <Attribute name="spot_light_strength" template="float" value="1.0"/>
      <Attribute name="diffuse_color" template="float3" value="1.0 1.0 1.0"/>
      <Attribute name="specular_color" template="float3" value="0.15 0.15 0.15"/>
      <Attribute name="specular_texture" template="string" value="Textures/Environment/cave_SPEC_v001"/>
      <Attribute name="env_ground_waves_amplitude" template="float" value="45"/>
      <Attribute name="env_ground_waves_frequency" template="float" value="0.00025"/>
      <Attribute name="env_ground_waves_hardness" template="float" value="15"/>
      <Attribute name="env_ground_waves_velocity" template="float" value="0.002"/>
    </Attributes>
    <Properties>
      <Property name="render" type="ProjectMagma.Simulation.EnvironmentRenderProperty"/>
      <Property name="collision" type="ProjectMagma.Simulation.Collision.CollisionProperty"/>
      <Property name="render_highlight" type="ProjectMagma.Simulation.RenderHighlightProperty"/>
    </Properties>
  </Entity>
  
  <Entity name="pillar_base_001" extends="pillar_base" abstract="true">
    <Attributes>
      <Attribute name="mesh" template="string" value="Models/Pillars/pillar_001"/>
    </Attributes>
  </Entity>

  <Entity name="pillar_base_002" extends="pillar_base" abstract="true">
    <Attributes>
      <Attribute name="mesh" template="string" value="Models/Pillars/pillar_002"/>
    </Attributes>
  </Entity>

  <Entity name="pillar_base_003" extends="pillar_base" abstract="true">
    <Attributes>
      <Attribute name="mesh" template="string" value="Models/Pillars/pillar_003"/>
    </Attributes>
  </Entity>
  
  <Entity name="powerup_base" abstract="true">
    <Attributes>
      <Attribute name="kind" template="string" value="powerup"/>
      <Attribute name="position" template="float3" value="0 0 0"/>
      <Attribute name="mesh" template="string" value="Models/Primitives/powerup"/>
      <Attribute name="scale" template="float3" value="12 12 12"/>
      <Attribute name="relative_position" template="float3" value="15 0 15"/>
      <Attribute name="pickup_sound" template="string" value="excellent"/>
      <Attribute name="bv_type" template="string" value="sphere"/>
      <Attribute name="diffuse_color" template="float3" value="1.0 1.0 1.0"/>
      <Attribute name="emissive_color" template="float3" value="0.0 0.0 0.0"/>
      <Attribute name="alpha" template="float" value="0.85"/>
      <Attribute name="persistent_squash" template="float2" value="1400.0 1.0"/>
    </Attributes>
    <Properties>
      <Property name="collision" type="ProjectMagma.Simulation.Collision.CollisionProperty"/>
      <Property name="shadow_cast" type="ProjectMagma.Simulation.ShadowCastProperty"/>
      <Property name="render" type="ProjectMagma.Simulation.BasicRenderProperty"/>
      <Property name="render_highlight" type="ProjectMagma.Simulation.RenderHighlightProperty"/>
    </Properties>
  </Entity>

  <Entity name="powerup_health" extends="powerup_base" abstract="true">
    <Attributes>
      <Attribute name="value" template="int" value="100"/>
      <Attribute name="diffuse_color" template="float3" value="0.9 0.5 0.5"/>
      <Attribute name="emissive_color" template="float3" value="0.1 0.0 0.0"/>
    </Attributes>
    <Properties>
      <Property name="controller" type="ProjectMagma.Simulation.PowerUpControllerHealth"/>
    </Properties>
  </Entity>

  <Entity name="powerup_energy" extends="powerup_base" abstract="true">
    <Attributes>
      <Attribute name="value" template="int" value="100"/>
      <Attribute name="diffuse_color" template="float3" value="0.5 0.5 0.9"/>
      <Attribute name="emissive_color" template="float3" value="0.0 0.0 0.1"/>
    </Attributes>
    <Properties>
      <Property name="controller" type="ProjectMagma.Simulation.PowerUpControllerEnergy"/>
    </Properties>
  </Entity>

  <Entity name="powerup_jumps" extends="powerup_base" abstract="true">
    <Attributes>
      <Attribute name="value" template="int" value="10"/>
      <Attribute name="diffuse_color" template="float3" value="0.5 0.9 0.5"/>
      <Attribute name="emissive_color" template="float3" value="0.0 0.1 0.0"/>
    </Attributes>
    <Properties>
      <Property name="controller" type="ProjectMagma.Simulation.PowerUpControllerJumps"/>
    </Properties>
  </Entity>

  <Entity name="powerup_repulsion" extends="powerup_base" abstract="true">
    <Attributes>
      <Attribute name="value" template="float" value="6"/>
      <Attribute name="diffuse_color" template="float3" value="0.9 0.9 0.5"/>
      <Attribute name="emissive_color" template="float3" value="0.1 0.1 0.0"/>
    </Attributes>
    <Properties>
      <Property name="controller" type="ProjectMagma.Simulation.PowerUpControllerRepulsion"/>
    </Properties>
  </Entity>

</Level>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/Instances/Stack/Renderer.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Level SYSTEM "../../Common/Levels.dtd">
<Level>

  <Includes>
    <Include name="Level\Common\Renderer\Templates.xml"/>
  </Includes>

  <Entity name="respawn_spot" extends="respawn_spot_base">
  </Entity>

  <Entity name="lavafire" extends="lavafire_base">
  </Entity>

  <Entity name="snow" extends="snow_base">
    <Attributes>
      <Attribute name="particles_per_second" template="float" value="60"/>
      <Attribute name="particle_lifetime" template="float" value="30"/>
      <Attribute name="max_alpha" template="float" value="0.9"/>
      <Attribute name="base_size" template="float" value="5"/>
      <Attribute name="random_size_modification" template="float" value="8"/>
      <Attribute name="melting_start" template="float" value="300"/>
      <Attribute name="melting_end" template="float" value="0"/>
    </Attributes>
  </Entity>

  <Entity name="fog" extends="fog_base">
    <Attributes>
      <Attribute name="fog_z_off" template="float" value="0.0005"/>
      <!-- big value: fog starts at smaller distance -->
      <Attribute name="fog_z_mul" template="float" value="1500"/>
      <Attribute name="fog_y_off" template="float" value="1"/>
      <!-- big value: fog ends at greater height -->
      <Attribute name="fog_y_mul" template="float" value="0.3"/>
      <Attribute name="fog_glob_mul" template="float" value="1.3"/>
      <Attribute name="fog_color" template="float3" value="0.9 0.5 0.1"/>
    </Attributes>
  </Entity>

  <Entity name="lava" extends="lava_base">
  </Entity>

  <Entity name="environment" extends="environment_base">
    <Attributes>
      <Attribute name="dir_light_1_bottom_amp_max_y" template="float" value="300.0"/>
      <Attribute name="dir_light_1_min_multiplier" template="float" value="1.0"/>
      <Attribute name="dir_light_1_max_multiplier" template="float" value="5.0"/>
    </Attributes>
  </Entity>

  <Entity name="lights" extends="lights_base">
  </Entity>

  <Entity name="tonemapping" extends="tonemapping_base">
    <Attributes>
      <Attribute name="in1" template="float3" value="1 1.4 1.0"/>
      <Attribute name="out1" template="float3" value="1 1.7 0.5"/>
      <Attribute name="in2" template="float3" value="2 2.7 2.0"/>
      <Attribute name="out2" template="float3" value="2 15 1.3"/>
    </Attributes>
  </Entity>

  <Entity name="topoverlay" extends="topoverlay_base">
    <Attributes>
      <Attribute name="strength" template="float" value="0.8"/>
    </Attributes>

  </Entity>

</Level>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/4Noobs.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Level SYSTEM "Levels.dtd">
<Level>

  <Includes>
    <Include name="Level\Constants.xml"/>
    <Include name="Level\Templates.xml"/>
  </Includes>
  <!-- "unique" game entities -->

  <Entity name="lava" extends="lava_base">
    <!-- don't mess with the lava, there is nothing to change here. -->
    <!-- if you know what you are doing, do it in the template. -->
  </Entity>

  <Entity name="cave" extends="cave_base">
    <!-- don't mess with the cave, there is nothing to change here. -->
    <!-- if you know what you are doing, do it in the template. -->
  </Entity>

  <!-- masses of game elements... -->

   <Entity name="island1" extends="island_base_grass1">
    <Attributes>
      <Attribute name="position" template="float3" value="0 150 0"/>
      <Attribute name="scale" template="float3" value="330 330 330"/>
    </Attributes>
     <Properties>
       <Property name="controller" type="ProjectMagma.Simulation.IslandNoMovementControllerProperty"/>
     </Properties>
   </Entity>
  
  <Entity name="powerup1" extends="powerup_health">
    <Attributes>
      <Attribute name="island_reference" template="string" value="island1"/>
      <Attribute name="relative_position" template="float3" value="100 10 100"/>
    </Attributes>
  </Entity>

  <Entity name="powerup2" extends="powerup_energy">
    <Attributes>
      <Attribute name="island_reference" template="string" value="island1"/>
      <Attribute name="relative_position" template="float3" value="-100 10 -100"/>
    </Attributes>
  </Entity>

</Level>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/Common/DynamicTemplates.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Level SYSTEM "Levels.dtd">
<Level>

  <Entity name="dynamic_entity" abstract="true">
    <Attributes>
      <Attribute name="dynamic" template="bool" value="true"/>
    </Attributes>
  </Entity>
  
  <Entity name="arrow_base" extends="dynamic_entity" abstract="true">
    <Attributes>
      <Attribute name="position" template="float3" value="0 0 0"/>
      <Attribute name="island" template="string" value=""/>

      <Attribute name="mesh" template="string" value="Models/Visualizations/arrow"/>
      <Attribute name="scale" template="float3" value="16 16 16"/>

      <Attribute name="alpha" template="float" value="0.5"/>
    </Attributes>
    <Properties>
      <Property name="controller" type="ProjectMagma.Simulation.ArrowControllerProperty"/>
    </Properties>
  </Entity>
  
  <Entity name="explosion_base" extends="dynamic_entity" abstract="true">
    <Attributes>
      <Attribute name="live_span" template="int" value="1000"/>

      <Attribute name="bv_type" template="string" value="sphere"/>
    </Attributes>
    <Properties>
      <Property name="collision" type="ProjectMagma.Simulation.Collision.CollisionProperty"/>
      <Property name="controller" type="ProjectMagma.Simulation.ExplosionControllerProperty"/>
    </Properties>
  </Entity>

  <Entity name="player_explosion_base" extends="explosion_base" abstract="true">
    <Attributes>
      <Attribute name="damage" template="int" value="20"/>
      
      <Attribute name="mesh" template="string" value="Models/Sfx/icespike_explosion"/>
      <Attribute name="scale" template="float3" value="35 35 35"/>
    </Attributes>
    <Properties>
      <Property name="render" type="ProjectMagma.Simulation.FireExplosionRenderProperty"/>
    </Properties>
  </Entity>

  <Entity name="ice_spike_explosion_base" extends="explosion_base" abstract="true">
    <Attributes>
      <Attribute name="mesh" template="string" value="Models/Sfx/icespike_explosion"/>
      <Attribute name="scale" template="float3" value="30 30 30"/>
    </Attributes>
    <Properties>
      <Property name="render" type="ProjectMagma.Simulation.IceExplosionRenderProperty"/>
    </Properties>
  </Entity>

  <Entity name="flamethrower_base" extends="dynamic_entity" abstract="true">
    <Attributes>
      <Attribute name="fueled" template="bool" value="true"/>

      <Attribute name="position" template="float3" value="0 0 0"/>
      <Attribute name="rotation" template="quaternion" value="0 0 0 1"/>
      <Attribute name="scale" template="float3" value="0 0 0"/>
      <Attribute name="full_scale" template="float3" value="120 120 120"/>

      <Attribute name="mesh" template="string" value="Models/Visualizations/flame_primitive"/>
      <Attribute name="diffuse_texture" template="string" value="Textures/flame"/>
      <Attribute name="alpha" template="float" value="0.75"/>

      <Attribute name="bv_type" template="string" value="alignedbox3tree"/>
    </Attributes>
    <Properties>
      <Property name="renderer" type="ProjectMagma.Simulation.FlamethrowerRenderProperty"/>
      <!--<Property name="renderer1" type="ProjectMagma.Simulation.BasicRenderProperty"/>-->
      <Property name="collision" type="ProjectMagma.Simulation.Collision.CollisionProperty"/>
      <Property name="controller" type="ProjectMagma.Simulation.FlamethrowerControllerProperty"/>
    </Properties>
  </Entity>
  
  <Entity name="ice_spike_base" extends="dynamic_entity" abstract="true">
    <Attributes>
      <Attribute name="dead" template="bool" value="false"/>

      <Attribute name="mesh" template="string" value="Models/Visualizations/icespike_primitive"/>
      <Attribute name="scale" template="float3" value="5 5 5"/>

      <Attribute name="bv_type" template="string" value="sphere"/>
    </Attributes>
    <Properties>
      <Property name="renderer" type="ProjectMagma.Simulation.IceSpikeRenderProperty"/>
      <Property name="collision" type="ProjectMagma.Simulation.Collision.CollisionProperty"/>
      <Property name="controller" type="ProjectMagma.Simulation.IceSpikeControllerProperty"/>
    </Properties>
  </Entity>

  <Entity name="spawn_light_base" extends="dynamic_entity" abstract="true">
    <Attributes>
      <Attribute name="position" template="float3" value="0 0 0"/>
    </Attributes>
    <Properties>
      <Property name="controller" type="ProjectMagma.Simulation.RespawnLightControllerProperty"/>
      <Property name="renderer" type="ProjectMagma.Simulation.RespawnLightRenderProperty"/> 
    </Properties>      
  </Entity>
  
</Level>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/RobotTemplates.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Level SYSTEM "Levels.dtd">
<Level>

  <Entity name="robot_base" abstract="true">
    <Attributes>
      <Attribute name="kind" template="string" value="robot"/>
      <Attribute name="scale" template="float3" value="13 13 13"/>
      <Attribute name="bv_type" template="string" value="sphere"/>
    </Attributes>
    <Properties>
      <Property name="shadow_cast" type="ProjectMagma.Simulation.ShadowCastProperty"/>
      <Property name="render" type="ProjectMagma.Simulation.RenderProperty"/>
      <Property name="render_highlight" type="ProjectMagma.Simulation.RenderHighlightProperty"/>
      <Property name="collision" type="ProjectMagma.Simulation.Collision.CollisionProperty"/>
      <Property name="controller" type="ProjectMagma.Simulation.PlayerControllerProperty"/>
    </Properties>
  </Entity>

  <Entity name="green_robot" extends="robot_base">
    <Attributes>
      <Attribute name="name" template="string" value="Bender"/>
      <Attribute name="description" template="string" value="A green Robot"/>
      <Attribute name="mesh" template="string" value="Models/player1_primitive"/>
    </Attributes>
  </Entity>

  <Entity name="yellow_robot" extends="robot_base">
    <Attributes>
      <Attribute name="name" template="string" value="I, Robot"/>
      <Attribute name="description" template="string" value="A yellow Robot"/>
      <Attribute name="mesh" template="string" value="Models/player2_primitive"/>
    </Attributes>
  </Entity>

</Level>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/Instances/MenuLevel/Simulation.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Level SYSTEM "..\..\Common\Levels.dtd">
<Level>

  <Includes>
    <Include name="Level\Common\Constants.xml"/>
    <Include name="Level\Common\Templates.xml"/>
  </Includes>

  <Entity name="sound" extends="sound_base">
    <Attributes>
      <Attribute name="background_music" template="string" value="Music/menu_level1"/>
    </Attributes>
  </Entity>


  <Entity name="player_constants" extends="player_constants_base">
  </Entity>

  <Entity name="island_constants" extends="island_constants_base">
  </Entity>

  <Entity name="powerup_constants" extends="powerup_constants_base">
  </Entity>
  
  <!-- "unique" game entities -->

  <Entity name="lava" extends="lava_base">
    <Attributes>
      <Attribute name="firefractal_texture" template="string" value="Textures/Lava/firefractal_orange"/>
    </Attributes>
    <!-- don't mess with the lava, there is nothing to change here. -->
    <!-- if you know what you are doing, do it in the template. -->
  </Entity>
  <Entity name="cave" extends="cave_base">
    <!-- don't mess with the cave, there is nothing to change here. -->
    <!-- if you know what you are doing, do it in the template. -->
  </Entity>


</Level>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/Instances/4Noobs/Simulation.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Level SYSTEM "..\..\Common\Levels.dtd">
<Level>

  <Includes>
    <Include name="Level\Common\Constants.xml"/>
    <Include name="Level\Common\Templates.xml"/>
  </Includes>

  <Entity name="sound" extends="sound_base">
  </Entity>
  
  <!-- "unique" game entities -->

  <Entity name="lava" extends="lava_base">
    <!-- don't mess with the lava, there is nothing to change here. -->
    <!-- if you know what you are doing, do it in the template. -->
    <Attributes>
      <Attribute name="firefractal_texture" template="string" value="Textures/Lava/firefractal_orange"/>
    </Attributes>
  </Entity>

  <Entity name="cave" extends="cave_base">
    <!-- don't mess with the cave, there is nothing to change here. -->
    <!-- if you know what you are doing, do it in the template. -->
  </Entity>

  <!-- masses of game elements... -->

   <Entity name="island1" extends="island_base_grass3">
    <Attributes>
      <Attribute name="position" template="float3" value="0 150 0"/>
      <Attribute name="scale" template="float3" value="550 550 550"/>
      <Attribute name="sinking_speed" template="float" value="0"/>

      <Attribute name="landing_offset_p1" template="float3" value="-100 150 -100"/>
      <Attribute name="landing_offset_p2" template="float3" value="-100 150 100"/>
      <Attribute name="landing_offset_p3" template="float3" value="100 150 -100"/>
      <Attribute name="landing_offset_p4" template="float3" value="100 150 100"/>

      <Attribute name="allow_props_collision" template="bool" value="true"/>
    </Attributes>
     <Properties>
       <Property name="controller" type="ProjectMagma.Simulation.IslandNoMovementControllerProperty"/>
     </Properties>
   </Entity>


  <Entity name="powerup1" extends="powerup_health">
    <Attributes>
      <Attribute name="island_reference" template="string" value="island1"/>
      <Attribute name="relative_position" template="float3" value="100 10 100"/>
    </Attributes>
  </Entity>

  <Entity name="powerup2" extends="powerup_energy">
    <Attributes>
      <Attribute name="island_reference" template="string" value="island1"/>
      <Attribute name="relative_position" template="float3" value="-100 10 -100"/>
    </Attributes>
  </Entity>

</Level>
