=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/Common/Levels.dtd
<!ELEMENT Level (Includes?, Entity*)>
<!ELEMENT Includes (Include*)>
<!ELEMENT Include EMPTY>
<!ELEMENT Entity (Attributes?, Properties?)>
<!ELEMENT Attributes (Attribute*)>
<!ELEMENT Properties (Property*)>
<!ELEMENT Attribute EMPTY>
<!ELEMENT Property EMPTY>
<!ATTLIST Include
  name CDATA #REQUIRED
>
<!ATTLIST Entity
  name ID #REQUIRED
  abstract CDATA "false"
  extends CDATA #IMPLIED
>
<!ATTLIST Attribute
  name CDATA #REQUIRED
  template (string|int|float|float2|float3|quaternion|bool) #REQUIRED
  value CDATA #REQUIRED
>
<!ATTLIST Property
  name CDATA #REQUIRED
  type CDATA #REQUIRED
  active CDATA "true"
>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/Common/RobotTemplates.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Level SYSTEM "Levels.dtd">
<Level>
  
  <Entity name="robot_base" abstract="true">
    <Attributes>
      <Attribute name="kind" template="string" value="player"/>
      <Attribute name="position" template="float3" value="0 0 0"/>
      <Attribute name="scale" template="float3" value="10 10 10"/>
      <Attribute name="bv_type" template="string" value="alignedbox3tree"/>
      <Attribute name="specular_color" template="float3" value="0.5 0.5 0.5"/>
      <Attribute name="specular_power" template="float" value="30"/>
      <Attribute name="emissive_color" template="float3" value="0.25 0.25 0.25"/>
      <Attribute name="alpha" template="float" value="1.0"/>
    </Attributes>
    <Properties>
      <Property name="collision" type="ProjectMagma.Simulation.Collision.CollisionProperty"/>
      <Property name="controller" type="ProjectMagma.Simulation.PlayerControllerProperty"/>
      <Property name="burnable" type="ProjectMagma.Simulation.BurnableProperty"/>
      <Property name="hud" type="ProjectMagma.Simulation.HUDProperty"/>
    </Properties>
  </Entity>

  <Entity name="rendered_robot_base" extends="robot_base" abstract="true">
    <Attributes>
      <Attribute name="mesh" template="string" value="Models/Player/robot_grp"/>
      <Attribute name="diffuse_texture" template="string" value="Textures/Player/robot_texture10"/>
      <Attribute name="specular_texture" template="string" value="Textures/Player/robot_spec"/>      
    </Attributes>
    <Properties>
      <Property name="render" type="ProjectMagma.Simulation.RobotRenderProperty"/>
    </Properties>
    </Entity>
  
  <Entity name="green_robot" extends="rendered_robot_base" abstract="true" >
      <Attributes>
        <Attribute name="color1" template="float3" value="0.24 0.84 0.16"/>
        <Attribute name="color2" template="float3" value="0.58 0.82 0.15"/>
      </Attributes>
  </Entity>

  <Entity name="orange_robot" extends="rendered_robot_base" abstract="true" >
    <Attributes>
      <Attribute name="color1" template="float3" value="0.97 0.51 0.17"/>
      <Attribute name="color2" template="float3" value="0.97 0.84 0.17"/>
    </Attributes>
  </Entity>

  <Entity name="blue_robot" extends="rendered_robot_base" abstract="true" >
    <Attributes>
      <Attribute name="color1" template="float3" value="0.15 0.51 0.83"/>
      <Attribute name="color2" template="float3" value="0.27 0.85 0.79"/>
    </Attributes>
  </Entity>

  <Entity name="purple_robot" extends="rendered_robot_base" abstract="true" >
    <Attributes>
      <Attribute name="color1" template="float3" value="0.91 0.08 0.64"/>
      <Attribute name="color2" template="float3" value="0.77 0.08 0.86"/>
    </Attributes>
  </Entity>  
  
</Level>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/IslandTemplates.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Level SYSTEM "Levels.dtd">
<Level>

  <Entity name="island_base" abstract="true">
    <Attributes>
      <Attribute name="kind" template="string" value="island"/>

      <Attribute name="position" template="float3" value="60 160 -30"/>
      <Attribute name="landing_offset" template="float3" value="0 70 0"/>
      <Attribute name="scale" template="float3" value="70 70 70"/>
      
      <Attribute name="velocity" template="float3" value="0 0 0"/>
      
      <Attribute name="diffuse_texture" template="string" value="Textures/Environment/environ_diffuse"/>
      <!--Attribute name="diffuse_texture" template="string" value="Textures/xna_logo"/-->
      <Attribute name="bv_type" template="string" value="alignedbox3tree"/>
      <Attribute name="lava_light_strength" template="float" value="10.0"/>
      
      <Attribute name="interactable" template="bool" value="false"/>

      <Attribute name="sinking_speed" template="float" value="14.0"/>
    </Attributes>
    <Properties>
      <Property name="collision" type="ProjectMagma.Simulation.Collision.CollisionProperty"/>
      <Property name="controller" type="ProjectMagma.Simulation.IslandCircualarMovementControllerProperty"/>
      <!--<Property name="death" type="ProjectMagma.Simulation.DeathProperty"/>-->
      <Property name="shadow_cast" type="ProjectMagma.Simulation.ShadowCastProperty"/>
      <Property name="render" type="ProjectMagma.Simulation.IslandRenderProperty"/>
      <!--Property name="render" type="ProjectMagma.Simulation.BasicRenderProperty"/-->
      <Property name="render_highlight" type="ProjectMagma.Simulation.RenderHighlightProperty"/>
    </Properties>
  </Entity>

  <!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -->
  
  <Entity name="island_base_burnt" extends="island_base" abstract="true">
    <Attributes>
      <Attribute name="wind_strength" template="float" value="0.0"/>
    </Attributes>
  </Entity>

  <Entity name="island_base_grass" extends="island_base" abstract="true">
    <Attributes>
      <Attribute name="wind_strength" template="float" value="0.03"/>
    </Attributes>
  </Entity>

  <Entity name="island_base_ice" extends="island_base" abstract="true">
    <Attributes>
      <Attribute name="wind_strength" template="float" value="0.0"/>
    </Attributes>
  </Entity>

  <!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -->

  <Entity name="island_base_burnt1" extends="island_base_burnt" abstract="true">
    <Attributes>
      <Attribute name="mesh" template="string" value="Models/Islands/burnt1_grp"/>
      <Attribute name="landing_offset" template="float3" value="30 70 0"/>
    </Attributes>
  </Entity>

  <Entity name="island_base_burnt2" extends="island_base_burnt" abstract="true">
    <Attributes>
      <Attribute name="mesh" template="string" value="Models/Islands/burnt2_grp"/>
    </Attributes>
  </Entity>

  <Entity name="island_base_burnt3" extends="island_base_burnt" abstract="true">
    <Attributes>
      <Attribute name="mesh" template="string" value="Models/Islands/burnt3_grp"/>
    </Attributes>
  </Entity>

  <!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -->

  <Entity name="island_base_grass1" extends="island_base_grass" abstract="true">
    <Attributes>
      <Attribute name="mesh" template="string" value="Models/Islands/grass1_grp"/>
    </Attributes>
  </Entity>

  <Entity name="island_base_grass2" extends="island_base_grass" abstract="true">
    <Attributes>
      <Attribute name="mesh" template="string" value="Models/Islands/grass2_grp"/>
    </Attributes>
  </Entity>

  <Entity name="island_base_grass3" extends="island_base_grass" abstract="true">
    <Attributes>
      <Attribute name="mesh" template="string" value="Models/Islands/grass3_grp"/>
      <Attribute name="landing_offset" template="float3" value="30 70 0"/>
    </Attributes>
  </Entity>

  <Entity name="island_base_grass4" extends="island_base_grass" abstract="true">
    <Attributes>
      <Attribute name="mesh" template="string" value="Models/Islands/grass4_grp"/>
      <Attribute name="landing_offset" template="float3" value="30 70 0"/>
    </Attributes>
  </Entity>

  <!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -->

  <Entity name="island_base_ice1" extends="island_base_ice" abstract="true">
    <Attributes>
      <Attribute name="mesh" template="string" value="Models/Islands/ice1_grp"/>
    </Attributes>
  </Entity>

  <Entity name="island_base_ice2" extends="island_base_ice" abstract="true">
    <Attributes>
      <Attribute name="mesh" template="string" value="Models/Islands/ice2_grp"/>
    </Attributes>
  </Entity>

  <Entity name="island_base_ice3" extends="island_base_ice" abstract="true">
    <Attributes>
      <Attribute name="mesh" template="string" value="Models/Islands/ice3_grp"/>
    </Attributes>
  </Entity>

  <Entity name="island_base_ice4" extends="island_base_ice" abstract="true">
    <Attributes>
      <Attribute name="mesh" template="string" value="Models/Islands/ice4_grp"/>
    </Attributes>
  </Entity>


</Level>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/Common/Renderer/Templates.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Level SYSTEM "../Levels.dtd">
<Level>
  <Entity name="snow_base" abstract="true">
    <Attributes>
      <Attribute name="particles_per_second" template="float" value="30"/>
    </Attributes>
  </Entity>
  
  <Entity name="fog">
  	<Attributes>
  		<Attribute name="fog_z_off" template="float" value="0.2"/>
  		<Attribute name="fog_z_mul" template="float" value="1.0"/>
  		<Attribute name="fog_y_off" template="float" value="0.2"/>
  		<Attribute name="fog_y_mul" template="float" value="0.1"/>
  		<Attribute name="fog_glob_mul" template="float" value="0.7"/>
  		<Attribute name="fog_color" template="float3" value="1 0.3 0"/>
  	</Attributes>
  </Entity>
</Level>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/CollisionTestLevel.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Level SYSTEM "Levels.dtd">
<Level>

  <Includes>
    <Include name="Level\Constants.xml"/>
    <Include name="Level\Templates.xml"/>
  </Includes>

  <!-- "unique" game entities -->

  <Entity name="camera1">
    <Attributes>
      <Attribute name="kind" template="string" value="camera"/>
      <Attribute name="position" template="float3" value="0 700 1800"/>
      <Attribute name="target" template="float3" value="0 150 0"/>
      <Attribute name="up" template="float3" value="0 1 0"/>
      <Attribute name="fov" template="float" value="18.5"/>
      <Attribute name="near_clip" template="float" value="1"/>
      <Attribute name="far_clip" template="float" value="10000"/>
    </Attributes>
    <Properties>
      <Property name="camera" type="ProjectMagma.Simulation.CameraProperty"/>
    </Properties>
  </Entity>

  <Entity name="lava">
    <Attributes>
      <Attribute name="kind" template="string" value="lava"/>
      <Attribute name="position" template="float3" value="0 0 0"/>
      <Attribute name="scale" template="float3" value="1000 1000 1000"/>
      <Attribute name="mesh" template="string" value="Models/lava_primitive"/>
    </Attributes>
    <Properties>
      <Property name="render" type="ProjectMagma.Simulation.RenderProperty"/>
      <Property name="render_highlight" type="ProjectMagma.Simulation.RenderHighlightProperty"/>
    </Properties>
  </Entity>

  <Entity name="cave1" extends="cave">
  </Entity>
  
  <!-- masses of game elements... -->
  
  <Entity name="pillar1" extends="pillar_base_001">
    <Attributes>
      <Attribute name="position" template="float3" value="0 0 0"/>
    </Attributes>
  </Entity>

  <Entity name="island1">
    <Attributes>
      <Attribute name="kind" template="string" value="island"/>
      <Attribute name="position" template="float3" value="60 160 0"/>
      <Attribute name="scale" template="float3" value="70 70 70"/>
      <Attribute name="velocity" template="float3" value="0 0 0"/>
      <Attribute name="acceleration" template="float3" value="0 0 0"/>
      <Attribute name="mesh" template="string" value="Models/gIsland_TypeA_001"/>
      <Attribute name="diffuse_texture" template="string" value="Textures/island_diffuse_v003"/>
      <Attribute name="bv_type" template="string" value="alignedbox3tree"/>
    </Attributes>
    <Properties>
      <Property name="collision" type="ProjectMagma.Simulation.Collision.CollisionProperty"/>
      <Property name="shadow_cast" type="ProjectMagma.Simulation.ShadowCastProperty"/>
      <Property name="render" type="ProjectMagma.Simulation.TexturedRenderProperty"/>
      <Property name="render_highlight" type="ProjectMagma.Simulation.RenderHighlightProperty"/>
    </Properties>
  </Entity>
</Level>
