=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/Common/Levels.dtd
<!ELEMENT Level (Includes?, Entity*)>
<!ELEMENT Includes (Include*)>
<!ELEMENT Include EMPTY>
<!ELEMENT Entity (Attributes?, Properties?)>
<!ELEMENT Attributes (Attribute*)>
<!ELEMENT Properties (Property*)>
<!ELEMENT Attribute EMPTY>
<!ELEMENT Property EMPTY>
<!ATTLIST Include
  name CDATA #REQUIRED
>
<!ATTLIST Entity
  name ID #REQUIRED
  abstract CDATA "false"
  extends CDATA #IMPLIED
>
<!ATTLIST Attribute
  name CDATA #REQUIRED
  template (string|int|float|float2|float3|quaternion|bool) #REQUIRED
  value CDATA #REQUIRED
>
<!ATTLIST Property
  name CDATA #REQUIRED
  type CDATA #REQUIRED
  active CDATA "true"
>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/Stack.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Level SYSTEM "Levels.dtd">
<Level>

  <Includes>
    <Include name="Level\Constants.xml"/>
    <Include name="Level\Templates.xml"/>
  </Includes>
  <!-- "unique" game entities -->

  <Entity name="lava" extends="lava_base">
    <!-- don't mess with the lava, there is nothing to change here. -->
    <!-- if you know what you are doing, do it in the template. -->
  </Entity>
  <Entity name="cave" extends="cave_base">
    <!-- don't mess with the cave, there is nothing to change here. -->
    <!-- if you know what you are doing, do it in the template. -->
  </Entity>

  <!-- masses of game elements... -->

  <Entity name="pillar1" extends="pillar_base_001">
    <Attributes>
      <Attribute name="position" template="float3" value="0 -10 0"/>
    </Attributes>
  </Entity>


  <Entity name="island1" extends="island_base_grass1">
    <Attributes>
      <Attribute name="position" template="float3" value="200 80 0"/>
    </Attributes>
  </Entity>

  <Entity name="island2" extends="island_base_grass2">
    <Attributes>
      <Attribute name="position" template="float3" value="0 120 200"/>
    </Attributes>
  </Entity>

  <Entity name="island3" extends="island_base_grass1">
    <Attributes>
      <Attribute name="position" template="float3" value="-200 160 0"/>
    </Attributes>
  </Entity>

  <Entity name="island4" extends="island_base_grass2">
    <Attributes>
      <Attribute name="position" template="float3" value="0 200 -200"/>
    </Attributes>
  </Entity>

  <Entity name="island11" extends="island_base_ice1">
    <Attributes>
      <Attribute name="position" template="float3" value="200 240 0"/>
    </Attributes>
  </Entity>

  <Entity name="island12" extends="island_base_ice2">
    <Attributes>
      <Attribute name="position" template="float3" value="0 280 200"/>
    </Attributes>
  </Entity>

  <Entity name="island13" extends="island_base_ice1">
    <Attributes>
      <Attribute name="position" template="float3" value="-200 320 0"/>
    </Attributes>
  </Entity>

  <Entity name="island14" extends="island_base_ice2">
    <Attributes>
      <Attribute name="position" template="float3" value="0 360 -200"/>
    </Attributes>
  </Entity>



  <Entity name="powerup1" extends="powerup_health">
    <Attributes>
      <Attribute name="island_reference" template="string" value="island4"/>
      <Attribute name="relative_position" template="float3" value="15 10 15"/>
    </Attributes>
  </Entity>

  <Entity name="powerup2" extends="powerup_energy">
    <Attributes>
      <Attribute name="island_reference" template="string" value="island2"/>
      <Attribute name="relative_position" template="float3" value="-20 10 -5"/>
    </Attributes>
  </Entity>

</Level>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/Instances/4vs4/Simulation.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Level SYSTEM "..\..\Common\Levels.dtd">
<Level>

  <Includes>
    <Include name="Level\Common\Constants.xml"/>
    <Include name="Level\Common\Templates.xml"/>
  </Includes>

  <Entity name="sound" extends="sound_base">
    <Attributes>
      <Attribute name="background_music" template="string" value="Music/background_janick"/>
    </Attributes>
  </Entity>

  <Entity name="player_constants" extends="player_constants_base">
  </Entity>

  <Entity name="island_constants" extends="island_constants_base">
  </Entity>

  <Entity name="powerup_constants" extends="powerup_constants_base">
  </Entity>


  <!-- "unique" game entities -->

  <Entity name="lava" extends="lava_base">
    <Attributes>
      <Attribute name="firefractal_texture" template="string" value="Textures/Lava/firefractal_orange"/>
    </Attributes>
    <!-- don't mess with the lava, there is nothing to change here. -->
    <!-- if you know what you are doing, do it in the template. -->
  </Entity>
  <Entity name="cave" extends="cave_base">
    <!-- don't mess with the cave, there is nothing to change here. -->
    <!-- if you know what you are doing, do it in the template. -->
  </Entity>

  <!-- masses of game elements... -->

  <Entity name="pillar1" extends="pillar_base_001">
    <Attributes>
      <Attribute name="position" template="float3" value="200 -50 200"/>
    </Attributes>
  </Entity>

  <Entity name="pillar2" extends="pillar_base_002">
    <Attributes>
      <Attribute name="position" template="float3" value="200 -50 -200"/>
    </Attributes>
  </Entity>

  <Entity name="pillar3" extends="pillar_base_002">
    <Attributes>
      <Attribute name="position" template="float3" value="-200 -50 200"/>
    </Attributes>
  </Entity>

  <Entity name="pillar4" extends="pillar_base_001">
    <Attributes>
      <Attribute name="position" template="float3" value="-200 -20 -200"/>
    </Attributes>
  </Entity>

  <Entity name="island1" extends="island_base_grass1">
    <Attributes>
      <Attribute name="position" template="float3" value="330 200 330"/>
    </Attributes>
  </Entity>

  <Entity name="island2" extends="island_base_grass1">
    <Attributes>
      <Attribute name="position" template="float3" value="330 200 -330"/>
    </Attributes>
  </Entity>

  <Entity name="island3" extends="island_base_grass1">
    <Attributes>
      <Attribute name="position" template="float3" value="-330 200 330"/>
    </Attributes>
  </Entity>

  <Entity name="island4" extends="island_base_grass1">
    <Attributes>
      <Attribute name="position" template="float3" value="-330 200 -330"/>
    </Attributes>
  </Entity>

  <Entity name="island5" extends="island_base_burnt1">
    <Attributes>
      <Attribute name="position" template="float3" value="0 -25 0"/>
      <Attribute name="direction" template="float3" value="0 0 -1"/>
    </Attributes>
    <Properties>
      <Property name="controller" type="ProjectMagma.Simulation.IslandStraightMovementControllerProperty"/>
    </Properties>
  </Entity>

  <Entity name="powerup1" extends="powerup_health">
    <Attributes>
      <Attribute name="island_reference" template="string" value="island4"/>
      <Attribute name="relative_position" template="float3" value="15 10 15"/>
    </Attributes>
  </Entity>

  <Entity name="powerup2" extends="powerup_energy">
    <Attributes>
      <Attribute name="island_reference" template="string" value="island2"/>
      <Attribute name="relative_position" template="float3" value="-20 10 -5"/>
    </Attributes>
  </Entity>

  <Entity name="powerup3" extends="powerup_life">
    <Attributes>
      <Attribute name="island_reference" template="string" value="island5"/>
      <Attribute name="relative_position" template="float3" value="-20 10 -5"/>
      <Attribute name="fixed" template="bool" value="true"/>

      <Attribute name="respawn_min_time" template="float" value="12000"/>
      <Attribute name="respawn_random_time" template="float" value="24000"/>
    </Attributes>
  </Entity>

</Level>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/Instances/4vs4/Renderer.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Level SYSTEM "../../Common/Levels.dtd">
<Level>

  <Includes>
    <Include name="Level\Common\Renderer\Templates.xml"/>
  </Includes>

  <Entity name="respawn_spot" extends="respawn_spot_base">
  </Entity>

  <Entity name="lavafire" extends="lavafire_base">
  </Entity>

  <Entity name="snow" extends="snow_base">
  </Entity>

  <Entity name="fog" extends="fog_base">
  </Entity>

  <Entity name="lava" extends="lava_base">
  </Entity>

  <Entity name="environment" extends="environment_base">
  </Entity>

  <Entity name="lights" extends="lights_base">
  </Entity>

  <Entity name="tonemapping" extends="tonemapping_base">
  </Entity>

  <Entity name="topoverlay" extends="topoverlay_base">
  </Entity>

</Level>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/Common/Constants.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Level SYSTEM "Levels.dtd">
<Level>

  <!-- constants -->

  <Entity name="constants_base" abstract="true">
    <Attributes>
      <Attribute name="gravity_acceleration" template="float3" value="0 -900 0"/>
      <Attribute name="max_gravity_speed" template="float" value="450"/>
    </Attributes>
  </Entity>
  
  <Entity name="player_constants_base" extends="constants_base" abstract="true">
    <Attributes>
      <Attribute name="respawn_time" template="int" value="1000"/>
      <Attribute name="respawn_min_distance_to_players" template="float" value="150"/>

      <Attribute name="max_health" template="int" value="100"/>
      <Attribute name="max_energy" template="int" value="100"/>
      <Attribute name="max_fuel" template="int" value="2500"/>

      <Attribute name="arrow_island_min_distance_factor" template="float" value="0.2"/>
      <Attribute name="arrow_island_max_distance_factor" template="float" value="0.90"/>
      <Attribute name="arrows_per_second" template="float" value="2.2"/>

      <Attribute name="lava_damage_per_second" template="int" value="100"/>
      <Attribute name="energy_recharge_per_second" template="int" value="8"/>

      <Attribute name="fuel_recharge_multiplier" template="float" value="1.2"/>
      <Attribute name="fuel_recharge_multiplier_island" template="float" value="4"/>
      <Attribute name="max_jetpack_speed" template="float" value="200"/>
      <Attribute name="jetpack_acceleration" template="float3" value="0 1600 0"/>

      <Attribute name="simple_jump_gravity_acceleration" template="float3" value="0 -2000 0"/>
      <Attribute name="simple_jump_height" template="float" value="100"/>
      
      <Attribute name="ice_spike_aim_angle" template="float" value="240"/>
      <Attribute name="ice_spike_energy_cost" template="int" value="35"/>
      <Attribute name="ice_spike_damage" template="int" value="25"/>
      <Attribute name="ice_spike_freeze_time" template="int" value="2500"/>
      <Attribute name="ice_spike_cooldown" template="int" value="1200"/>
      <Attribute name="ice_spike_rising_time" template="int" value="500"/>
      <Attribute name="ice_spike_initial_speed_multiplier" template="float3" value="0 300 0"/>
      <Attribute name="ice_spike_max_speed" template="float" value="440"/>
      <Attribute name="ice_spike_gravity_acceleration" template="float3" value="0 -200 0"/>
      <Attribute name="ice_spike_homing_acceleration" template="float" value="5000"/>
      <Attribute name="ice_spike_pillar_force_radius" template="float" value="15"/>
      <Attribute name="ice_spike_island_force_radius" template="float" value="60"/>
      <Attribute name="ice_spike_lifetime" template="int" value="6000"/>
      <Attribute name="ice_spike_death_timeout" template="int" value="3500"/>

      <Attribute name="running_energy_cost_per_second" template="int" value="12"/>
      <Attribute name="frozen_slowdown_divisor" template="float" value="6"/>

      <Attribute name="flamethrower_aim_angle" template="float" value="90"/>
      <Attribute name="flamethrower_warmup_time" template="int" value="1000"/>
      <Attribute name="flamethrower_warmup_energy_cost" template="int" value="15"/>
      <Attribute name="flamethrower_energy_per_second" template="int" value="5"/>
      <Attribute name="flamethrower_cooldown_time" template="int" value="600"/>
      <Attribute name="flamethrower_turn_flame_increase" template="float" value="1"/>
      <Attribute name="flamethrower_turn_scale" template="float" value="0.6"/>
      <Attribute name="flamethrower_damage_per_second" template="int" value="40"/>
      <Attribute name="flamethrower_after_burn_time" template="int" value="300"/>
      <Attribute name="flamethrower_offset" template="float3" value="-12 45 -20"/>

      <Attribute name="hit_damage" template="int" value="20"/>
      <Attribute name="hit_cooldown" template="int" value="250"/>
      <Attribute name="hit_pushback_velocity_multiplier" template="float3" value="500 200 500"/>
      <Attribute name="player_pushback_deacceleration" template="float" value="600"/>
      <Attribute name="player_pushback_velocity_multiplier" template="float" value="120"/>

      <Attribute name="island_aim_angle" template="float" value="360"/>
      <Attribute name="island_aim_angle_eps" template="float" value="30"/>
      <Attribute name="island_reselection_max_value" template="float" value="0.9"/>
      <Attribute name="island_reselection_timeout" template="float" value="100"/>
      <Attribute name="island_deselection_timeout" template="float" value="200"/>
      <Attribute name="island_jump_free_range" template="float" value="250"/>
      <Attribute name="island_jump_arc_height" template="float" value="220"/>
      <Attribute name="island_jump_speed" template="float" value="20"/>

      <Attribute name="island_repulsion_start_velocity_multiplier" template="float" value="60"/>
      <Attribute name="island_repulsion_acceleration" template="float" value="1000"/>
      <Attribute name="island_repulsion_start_min_energy" template="int" value="10"/>
      <Attribute name="island_repulsion_start_energy_cost" template="int" value="6"/>
      <Attribute name="island_repulsion_energy_cost_per_second" template="int" value="16"/>

      <Attribute name="island_non_walking_range_multiplier" template="float" value="12"/>
      <Attribute name="island_non_walking_inwards_acceleration" template="float" value="2000"/>
      <Attribute name="x_axis_walk_multiplier" template="float" value="140"/>
      <Attribute name="z_axis_walk_multiplier" template="float" value="140"/>
      <Attribute name="x_axis_run_multiplier" template="float" value="330"/>
      <Attribute name="z_axis_run_multiplier" template="float" value="330"/>
      <Attribute name="x_axis_jetpack_multiplier" template="float" value="200"/>
      <Attribute name="z_axis_jetpack_multiplier" template="float" value="200"/>
    </Attributes>
  </Entity>

  <Entity name="island_constants_base" extends="constants_base" abstract="true">
    <Attributes>
      <!-- all islands -->
      <Attribute name="movement_acceleration" template="float" value="600"/>

      <Attribute name="rising_delay" template="int" value="800"/>
      <Attribute name="repositioning_acceleraton" template="float" value="800" />

      <Attribute name="scale_health_multiplier" template="float" value="1.8"/>

      <Attribute name="repulsion_deacceleration" template="float" value="400"/>
      <Attribute name="collision_damping" template="float" value="0.9"/>

      <!-- circular moving islands-->
      <Attribute name="angle_speed" template="float" value="0.6"/>
      <Attribute name="contact_pushback_multiplier" template="float" value="200"/>

      <!-- physical islands -->
      <Attribute name="random_strength" template="float" value="1200"/>
      <Attribute name="max_velocity" template="float" value="100"/>
      <Attribute name="damping" template="float" value="0.001"/>

      <Attribute name="pillar_elasticity" template="float" value="0.1"/>
      <Attribute name="pillar_attraction" template="float" value="0.0001"/>
      <Attribute name="pillar_repulsion" template="float" value="0.03"/>
    </Attributes>
  </Entity>

  <Entity name="powerup_constants_base" extends="constants_base" abstract="true">
    <Attributes>
      <Attribute name="respawn_min_time" template="float" value="5000"/>
      <Attribute name="respawn_random_time" template="float" value="10000"/>

      <Attribute name="respawn_min_distance_to_others" template="float" value="200"/>
    </Attributes>
  </Entity>
  
</Level>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/Instances/TestLevel/Simulation.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Level SYSTEM "../../Common/Levels.dtd">
<Level>

  <Includes>
    <Include name="Level\Common\Constants.xml"/>
    <Include name="Level\Common\Templates.xml"/>
  </Includes>


  <Entity name="player_constants" extends="player_constants_base">
  </Entity>

  <Entity name="island_constants" extends="island_constants_base">
  </Entity>

  <Entity name="powerup_constants" extends="powerup_constants_base">
  </Entity>
  
  
  <Entity name="sound" extends="sound_base">
    <Attributes>
      <Attribute name="background_music" template="string" value="Music/menu_level1:0.8"/>
    </Attributes>
  </Entity>

  <!-- "unique" game entities -->

  <Entity name="lava" extends="lava_base">
    <Attributes>
      <Attribute name="firefractal_texture" template="string" value="Textures/Lava/firefractal_orange"/>
    </Attributes>
    <!-- don't mess with the lava, there is nothing to change here. -->
    <!-- if you know what you are doing, do it in the template. -->
  </Entity>

  <Entity name="cave" extends="cave_base">
    <!-- don't mess with the cave, there is nothing to change here. -->
    <!-- if you know what you are doing, do it in the template. -->
  </Entity>

  
  <!-- masses of game elements... -->

  <Entity name="pillar1" extends="pillar_base_001">
    <Attributes>
      <Attribute name="position" template="float3" value="230 -50 260"/>
    </Attributes>
  </Entity>

  <Entity name="pillar2" extends="pillar_base_003">
    <Attributes>
      <Attribute name="position" template="float3" value="-300 -50 150"/>
    </Attributes>
  </Entity>

  <Entity name="pillar3" extends="pillar_base_002">
    <Attributes>
      <Attribute name="position" template="float3" value="200 -50 -120"/>
    </Attributes>
  </Entity>

  <Entity name="pillar4" extends="pillar_base_001">
    <Attributes>
      <Attribute name="position" template="float3" value="-100 -20 0"/>
    </Attributes>
  </Entity>

  <Entity name="pillar5" extends="pillar_base_003">
    <Attributes>
      <Attribute name="position" template="float3" value="10 -20 -300"/>
    </Attributes>
  </Entity>



  <Entity name="island1" extends="island_base_burnt1">
    <Attributes>
      <Attribute name="position" template="float3" value="-150 65 120"/>
      <Attribute name="fixed" template="bool" value="false"/>
    </Attributes>
    <Properties>
      <Property name="controller" type="ProjectMagma.Simulation.IslandNoMovementControllerProperty"/>
    </Properties>
  </Entity>

  <Entity name="island1a" extends="island_base_burnt1">
    <Attributes>
      <Attribute name="position" template="float3" value="-0 65 120"/>
      <Attribute name="fixed" template="bool" value="false"/>

      <!-- new test texture -->
      <Attribute name="diffuse_texture" template="string" value="Textures/Environment/environ_diffuse_test_alpha"/>
    </Attributes>
    <Properties>
      <Property name="controller" type="ProjectMagma.Simulation.IslandNoMovementControllerProperty"/>

      <!-- test alpha rendering -->
      <Property name="render" type="ProjectMagma.Simulation.AlphaIslandRenderProperty"/>
    </Properties>
  </Entity>

  <Entity name="island2" extends="island_base_burnt2">
    <Attributes>
      <Attribute name="position" template="float3" value="150 100 160"/>
    </Attributes>
    <Properties>
      <Property name="controller" type="ProjectMagma.Simulation.IslandNoMovementControllerProperty"/>
    </Properties>
  </Entity>

  <Entity name="island4" extends="island_base_grass1">
    <Attributes>
      <Attribute name="position" template="float3" value="350 180 120"/>
    </Attributes>
    <Properties>
      <Property name="controller" type="ProjectMagma.Simulation.IslandNoMovementControllerProperty"/>
    </Properties>
  </Entity>

  <Entity name="island6" extends="island_base_grass1">
    <Attributes>
      <Attribute name="position" template="float3" value="60 200 -30"/>
    </Attributes>
    <Properties>
      <Property name="controller" type="ProjectMagma.Simulation.IslandNoMovementControllerProperty"/>
    </Properties>
  </Entity>

  <Entity name="island8" extends="island_base_grass3">
    <Attributes>
      <Attribute name="position" template="float3" value="-250 240 220"/>
    </Attributes>
    <Properties>
      <Property name="controller" type="ProjectMagma.Simulation.IslandNoMovementControllerProperty"/>
    </Properties>
  </Entity>

  <Entity name="island10" extends="island_base_grass2">
    <Attributes>
      <Attribute name="position" template="float3" value="-90 280 -280"/>
    </Attributes>
    <Properties>
      <Property name="controller" type="ProjectMagma.Simulation.IslandNoMovementControllerProperty"/>
    </Properties>
  </Entity>

  <Entity name="island12" extends="island_base_ice2">
    <Attributes>
      <Attribute name="position" template="float3" value="-140 400 -240"/>
      <Attribute name="fixed" template="bool" value="false"/>
    </Attributes>
    <Properties>
      <Property name="controller" type="ProjectMagma.Simulation.IslandNoMovementControllerProperty"/>
    </Properties>
  </Entity>

  <Entity name="island13" extends="island_base_ice3">
    <Attributes>
      <Attribute name="position" template="float3" value="140 330 240"/>
    </Attributes>
    <Properties>
      <Property name="controller" type="ProjectMagma.Simulation.IslandNoMovementControllerProperty"/>
    </Properties>
  </Entity>

  

  <Entity name="powerup1" extends="powerup_health">
    <Attributes>
      <Attribute name="island_reference" template="string" value="island4"/>
      <Attribute name="relative_position" template="float3" value="15 10 15"/>
    </Attributes>
  </Entity>

  <Entity name="powerup2" extends="powerup_energy">
    <Attributes>
      <Attribute name="island_reference" template="string" value="island2"/>
      <Attribute name="relative_position" template="float3" value="-20 10 -5"/>
    </Attributes>
  </Entity>

  <!--
  <Entity name="powerup3" extends="powerup_jumps">
    <Attributes>
      <Attribute name="island_reference" template="string" value="island11"/>
      <Attribute name="relative_position" template="float3" value="20 10 10"/>
    </Attributes>
  </Entity>

  <Entity name="powerup4" extends="powerup_repulsion">
    <Attributes>
      <Attribute name="island_reference" template="string" value="island12"/>
      <Attribute name="relative_position" template="float3" value="20 10 10"/>
    </Attributes>
  </Entity>
  -->

</Level>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/Instances/StaircaseOfDoom/Simulation.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Level SYSTEM "..\..\Common\Levels.dtd">
<Level>

  <Includes>F
    <Include name="Level\Common\Constants.xml"/>
    <Include name="Level\Common\Templates.xml"/>
  </Includes>
  <!-- "unique" game entities -->

  <Entity name="sound" extends="sound_base">
  </Entity>
  
  <Entity name="lava" extends="lava_base">
    <Attributes>
      <Attribute name="firefractal_texture" template="string" value="Textures/Lava/firefractal_red"/>
    </Attributes>
    <!-- don't mess with the lava, there is nothing to change here. -->
    <!-- if you know what you are doing, do it in the template. -->
  </Entity>
  <Entity name="cave" extends="cave_base">
    <!-- don't mess with the cave, there is nothing to change here. -->
    <!-- if you know what you are doing, do it in the template. -->
  </Entity>

  <!-- masses of game elements... -->
  
  <Entity name="island1" extends="island_base_grass1">
    <Attributes>
      <Attribute name="position" template="float3" value="0 420 -600"/>
      <Attribute name="direction" template="float3" value="1 0 0"/>
    </Attributes>
    <Properties>
      <Property name="controller" type="ProjectMagma.Simulation.IslandStraightMovementControllerProperty"/>
    </Properties>
  </Entity>

</Level>

=== cfo82/Magmageddon/src/ProjectMagma/ProjectMagma/Content/Level/Constants.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Level SYSTEM "Levels.dtd">
<Level>

  <!-- constants -->

  <Entity name="player_constants">
    <Attributes>
      <Attribute name="respawn_time" template="int" value="1000"/>

      <Attribute name="max_health" template="int" value="100"/>
      <Attribute name="max_energy" template="int" value="100"/>
      <Attribute name="max_fuel" template="int" value="2500"/>

      <Attribute name="energy_recharge_interval" template="int" value="200"/>

      <Attribute name="fuel_recharge_multiplier" template="float" value="0.75"/>
      <Attribute name="fuel_recharge_multiplier_island" template="float" value="1.2"/>
      <Attribute name="max_jetpack_speed" template="float" value="150"/>
      <Attribute name="jetpack_acceleration" template="float3" value="0 1300 0"/>

      <Attribute name="gravity_acceleration" template="float3" value="0 -900 0"/>
      <Attribute name="max_gravity_speed" template="float" value="450"/>

      <Attribute name="pushback_contact_velocity_multiplier" template="float" value="80"/>
      <Attribute name="pushback_deacceleration_multiplier" template="float" value="300"/>

      <Attribute name="ice_spike_speed" template="float" value="300"/>
      <Attribute name="ice_spike_up_speed" template="float" value="200"/>
      <Attribute name="ice_spike_aim_angle" template="float" value="45"/>
      <Attribute name="ice_spike_energy_cost" template="int" value="2"/>
      <Attribute name="ice_spike_damage" template="int" value="1"/>
      <Attribute name="ice_spike_freeze_time" template="int" value="200"/>
      <Attribute name="ice_spike_cooldown" template="int" value="50"/>

      <Attribute name="flamethrower_warmup_time" template="int" value="600"/>
      <Attribute name="flamethrower_warmup_energy_cost" template="int" value="20"/>
      <Attribute name="flamethrower_energy_per_second" template="int" value="5"/>
      <Attribute name="flamethrower_cooldown_time" template="int" value="400"/>
      <Attribute name="flamethrower_turn_flame_increase" template="float" value="1"/>
      <Attribute name="flamethrower_turn_scale" template="float" value="0.6"/>
      <Attribute name="flamethrower_player_damage_per_second" template="int" value="8"/>
      <Attribute name="flamethrower_island_damage_per_second" template="int" value="50"/>

      <Attribute name="hit_damage" template="int" value="20"/>
      <Attribute name="hit_cooldown" template="int" value="250"/>
      <Attribute name="hit_pushback_velocity_multiplier" template="float" value="200"/>

      <Attribute name="x_axis_movement_multiplier" template="float" value="140"/>
      <Attribute name="z_axis_movement_multiplier" template="float" value="140"/>
      <Attribute name="x_axis_jetpack_multiplier" template="float" value="200"/>
      <Attribute name="z_axis_jetpack_multiplier" template="float" value="200"/>
    </Attributes>
  </Entity>

  <Entity name="island_constants">
    <Attributes>
      <Attribute name="random_strength" template="float" value="1200"/>
      <Attribute name="max_velocity" template="float" value="100"/>
      <Attribute name="damping" template="float" value="0.001"/>

      <Attribute name="pillar_elasticity" template="float" value="0.1"/>
      <Attribute name="pillar_attraction" template="float" value="0.0001"/>
      <Attribute name="pillar_repulsion" template="float" value="0.03"/>
      <Attribute name="sinking_speed" template="float" value="20.0"/>
      <Attribute name="rising_speed" template="float" value="30.0"/>
    </Attributes>
  </Entity>

</Level>
